# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_form1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form1(object):
    def setupUi(self, form1):
        form1.setObjectName("form1")
        form1.resize(828, 463)
        self.lblShow = QtWidgets.QLabel(form1)
        self.lblShow.setGeometry(QtCore.QRect(200, 50, 611, 361))
        self.lblShow.setFrameShape(QtWidgets.QFrame.Box)
        self.lblShow.setText("")
        self.lblShow.setScaledContents(True)
        self.lblShow.setObjectName("lblShow")
        self.cmdOK = QtWidgets.QPushButton(form1)
        self.cmdOK.setGeometry(QtCore.QRect(260, 340, 131, 41))
        self.cmdOK.setObjectName("cmdOK")
        self.cmdCancel = QtWidgets.QPushButton(form1)
        self.cmdCancel.setGeometry(QtCore.QRect(620, 340, 131, 41))
        self.cmdCancel.setObjectName("cmdCancel")
        self.groupBox = QtWidgets.QGroupBox(form1)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 171, 431))
        self.groupBox.setObjectName("groupBox")
        self.lst_client = QtWidgets.QListWidget(self.groupBox)
        self.lst_client.setGeometry(QtCore.QRect(10, 20, 151, 401))
        self.lst_client.setObjectName("lst_client")

        self.retranslateUi(form1)
        QtCore.QMetaObject.connectSlotsByName(form1)

    def retranslateUi(self, form1):
        _translate = QtCore.QCoreApplication.translate
        form1.setWindowTitle(_translate("form1", "unity通信测试窗口"))
        self.cmdOK.setText(_translate("form1", "OK"))
        self.cmdCancel.setText(_translate("form1", "Cancel"))
        self.groupBox.setTitle(_translate("form1", "客户端列表"))
