# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_frmInitialize.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmInitialize(object):
    def setupUi(self, frmInitialize):
        frmInitialize.setObjectName("frmInitialize")
        frmInitialize.resize(400, 300)
        self.label = QtWidgets.QLabel(frmInitialize)
        self.label.setGeometry(QtCore.QRect(100, 40, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(frmInitialize)
        self.label_2.setGeometry(QtCore.QRect(40, 114, 72, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(frmInitialize)
        self.label_3.setGeometry(QtCore.QRect(40, 160, 72, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.txtHost = QtWidgets.QLineEdit(frmInitialize)
        self.txtHost.setGeometry(QtCore.QRect(120, 110, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std")
        font.setPointSize(12)
        self.txtHost.setFont(font)
        self.txtHost.setObjectName("txtHost")
        self.txtPort = QtWidgets.QLineEdit(frmInitialize)
        self.txtPort.setGeometry(QtCore.QRect(120, 160, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std")
        font.setPointSize(12)
        self.txtPort.setFont(font)
        self.txtPort.setObjectName("txtPort")
        self.cmdStart = QtWidgets.QPushButton(frmInitialize)
        self.cmdStart.setGeometry(QtCore.QRect(70, 220, 121, 31))
        self.cmdStart.setObjectName("cmdStart")
        self.cmdExit = QtWidgets.QPushButton(frmInitialize)
        self.cmdExit.setGeometry(QtCore.QRect(230, 220, 121, 31))
        self.cmdExit.setObjectName("cmdExit")

        self.retranslateUi(frmInitialize)
        QtCore.QMetaObject.connectSlotsByName(frmInitialize)

    def retranslateUi(self, frmInitialize):
        _translate = QtCore.QCoreApplication.translate
        frmInitialize.setWindowTitle(_translate("frmInitialize", "服务器设置"))
        self.label.setText(_translate("frmInitialize", "Unity服务器设置"))
        self.label_2.setText(_translate("frmInitialize", "主机: "))
        self.label_3.setText(_translate("frmInitialize", "端口: "))
        self.cmdStart.setText(_translate("frmInitialize", "启动"))
        self.cmdExit.setText(_translate("frmInitialize", "退出"))
